// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostalRegistry.Producer.Ldes;

#nullable disable

namespace PostalRegistry.Producer.Ldes.Migrations
{
    [DbContext(typeof(ProducerContext))]
    partial class ProducerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DesiredState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DesiredStateChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.HasKey("Name");

                    b.ToTable("ProjectionStates", "PostalRegistryProducerLdes");
                });

            modelBuilder.Entity("PostalRegistry.Producer.Ldes.PostalInformationDetail", b =>
                {
                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsRetired")
                        .HasColumnType("bit");

                    b.Property<string>("NisCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("VersionTimestampAsDateTimeOffset")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("VersionTimestamp");

                    b.Property<string>("_namesDutchBackingProperty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamesDutch");

                    b.Property<string>("_namesEnglishBackingProperty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamesEnglish");

                    b.Property<string>("_namesFrenchBackingProperty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamesFrench");

                    b.Property<string>("_namesGermanBackingProperty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NamesGerman");

                    b.HasKey("PostalCode");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("PostalCode"));

                    b.HasIndex("NisCode");

                    b.ToTable("PostalInformation", "PostalRegistryProducerLdes");
                });
#pragma warning restore 612, 618
        }
    }
}
